### ISSUE TITLE
Add ability to create different launch profiles

### ISSUE THREAD

**Issue by Kaidero** [JonathanWThom/opener#3]
it would be cool to be able to define many custom app groups  and launch them by name.
maybe with `opener <profile_name>` or something.

**Comment by JonathanWThom** [comment]
@Kaidero I added this here! https://github.com/JonathanWThom/opener/commit/15f7bc2271a8d87af4f085bf1d7cc2bdee87b741

The config object will look like this now:
```
{
    "default": [
        "Google Chrome",
        "Slack",
        "Calendar",
        "Notes",
        "Postico"
    ],
    "weekend": [
        "Spotify",
        "News"
    ]
}
```

And then you can run `opener -g weekend` to open the weekend group. If you leave out the `-g` flag, it'll just use your default list. 

Thanks for the great suggestion!
